[package]
name = "recipe-004-basic-data-types"
version = "0.1.0"
edition = "2024"

[dependencies]
ruchy = "=3.194.0"

[dev-dependencies]
proptest = "1.4.0"

[[bin]]
name = "basic-data-types"
path = "src/main.ruchy"
