[package]
name = "recipe-007-structs,-classes,-and-methods"
version = "0.1.0"
edition = "2024"

[dependencies]
ruchy = "=3.194.0"

[dev-dependencies]
proptest = "1.4.0"

[[bin]]
name = "structs,-classes,-and-methods"
path = "src/main.ruchy"
